INSERT INTO news (inst_id, date, title, description, image_url) VALUES (1, 'Mon Nov 29 14:22:00 BRT 2021', 'He hated that he loved what she hated about hate.', 'Ambusher maze wocka wocka fruit Pac-Man Fever arcade Galaxian Boss power up intermission. He hated that he loved what she hated about hate. Pac-Man Namco Toru Iwatani Pac-Man Fever maze dots. The external scars tell only part of the story. Apple Speedy maze wocka wocka flash chase Pakkuman paku-paku dots pizza missing slice. Fluffy pink unicorns are a popular status symbol among macho men. Key Crybaby slow guy maze dots Power Pellets flash Midway chaser Pinky cherry Puck Man ghosts. Shadow pink ghosts kill screen yellow disk video game maze console power up dots Midway. He found his art never progressed when he literally used his sweat and tears. Clyde blue enemies flash dots wocka maze monsters ghosts red chaser.', 'assets/images/news/new_1.jpg');

INSERT INTO news (inst_id, date, title, description, image_url) VALUES (1, 'Mon Nov 29 19:26:04 BRT 2021', 'Fluffy pink unicorns are a popular men.', 'She was disgusted he couldn’t tell the difference between lemonade and limeade. Shadow dots strawberry Pac-Man Midway chaser Pinky kill screen. Pac-Man bell ghosts Pokey strawberry flash blue enemies Namco Japan chaser dots dots Pakkuman. He had a hidden stash underneath the floorboards in the back room of the house. I think I will buy the red car, or I will lease the blue one. She had the gift of being able to paint songs. Ambusher maze wocka wocka fruit Pac-Man Fever arcade Galaxian Boss power up intermission. I hear that Nancy is very pretty. She learned that water bottles are no longer just to hold liquid, but they''re also status symbols. The external scars tell only part of the story.', 'assets/images/news/new_2.jpg');

INSERT INTO news (inst_id, date, title, description, image_url) VALUES (2, 'Mon Nov 29 13:15:55 BRT 2021', 'I hear that Nancy is very pretty.', 'He found his art never progressed when he literally used his sweat and tears. I hear that Nancy is very pretty. I think I will buy the red car, or I will lease the blue one. He had a hidden stash underneath the floorboards in the back room of the house. Ghosts dots cherry Blinky Pac-Man Power Pellets fruit. Key Crybaby slow guy maze dots Power Pellets flash Midway chaser Pinky cherry Puck Man ghosts. Don''t put peanut butter on the dog''s nose. Apple Speedy maze wocka wocka flash chase Pakkuman paku-paku dots pizza missing slice. Pac-Man Inky bashfull orange dots blue enemies ghosts Toru Iwatani Puck Man power up. He was willing to find the depths of the rabbit hole in order to be with her.', 'assets/images/news/new_3.jpg');

INSERT INTO news (inst_id, date, title, description, image_url) VALUES (2, 'Mon Nov 29 15:26:04 BRT 2021', 'The old apple revels in its authority.', 'Patricia loves the sound of nails strongly pressed against the chalkboard. Flying fish few by the space station. Orange fickle blue guy maze chase. He found his art never progressed when he literally used his sweat and tears. She was disgusted he couldn’t tell the difference between lemonade and limeade. Shadow dots strawberry Pac-Man Midway chaser Pinky kill screen. The external scars tell only part of the story. Pac-Man Namco Toru Iwatani Pac-Man Fever maze dots. Pac-Man bell ghosts Pokey strawberry flash blue enemies Namco Japan chaser dots dots Pakkuman. I think I will buy the red car, or I will lease the blue one.', 'assets/images/news/new_4.jpg');

INSERT INTO news (inst_id, date, title, description, image_url) VALUES (3, 'Mon Nov 29 09:26:04 BRT 2021', 'The external scars tell only part of the story.', 'Orange fickle blue guy maze chase. Pac-Man bell ghosts Pokey strawberry flash blue enemies Namco Japan chaser dots dots Pakkuman. The external scars tell only part of the story. Don''t put peanut butter on the dog''s nose. Ambusher maze wocka wocka fruit Pac-Man Fever arcade Galaxian Boss power up intermission. He hated that he loved what she hated about hate. Arcade cabinets retro Melon dots maza Pac-Man chase red Namco fruit wocka paku-paku 1980. She learned that water bottles are no longer just to hold liquid, but they''re also status symbols. Clyde blue enemies flash dots wocka maze monsters ghosts red chaser. I think I will buy the red car, or I will lease the blue one.', 'assets/images/news/new_5.jpg');

INSERT INTO news (inst_id, date, title, description, image_url) VALUES (3, 'Mon Nov 29 15:26:04 BRT 2021', 'Orange fickle blue guy maze chase.', 'Shadow pink ghosts kill screen yellow disk video game maze console power up dots Midway. She had the gift of being able to paint songs. Don''t put peanut butter on the dog''s nose. The old apple revels in its authority. She learned that water bottles are no longer just to hold liquid, but they''re also status symbols. Ghosts dots cherry Blinky Pac-Man Power Pellets fruit. I hear that Nancy is very pretty. The external scars tell only part of the story. Pac-Man Inky bashfull orange dots blue enemies ghosts Toru Iwatani Puck Man power up. Key Crybaby slow guy maze dots Power Pellets flash Midway chaser Pinky cherry Puck Man ghosts.', 'assets/images/news/new_6.jpg');

INSERT INTO news (inst_id, date, title, description, image_url) VALUES (4, 'Mon Nov 29 10:15:05 BRT 2021', 'I hear that Nancy is very pretty.', 'He hated that he loved what she hated about hate. Don''t put peanut butter on the dog''s nose. She had the gift of being able to paint songs. He found his art never progressed when he literally used his sweat and tears. Flying fish few by the space station. Key Crybaby slow guy maze dots Power Pellets flash Midway chaser Pinky cherry Puck Man ghosts. The external scars tell only part of the story. Clyde blue enemies flash dots wocka maze monsters ghosts red chaser. Pac-Man Namco Toru Iwatani Pac-Man Fever maze dots. Shadow dots strawberry Pac-Man Midway chaser Pinky kill screen.', 'assets/images/news/new_7.jpg');

INSERT INTO news (inst_id, date, title, description, image_url) VALUES (4, 'Mon Nov 29 19:21:07 BRT 2021', 'The old apple revels in its authority.', 'Orange fickle blue guy maze chase. Ambusher maze wocka wocka fruit Pac-Man Fever arcade Galaxian Boss power up intermission. Pac-Man Namco Toru Iwatani Pac-Man Fever maze dots. Key Crybaby slow guy maze dots Power Pellets flash Midway chaser Pinky cherry Puck Man ghosts. He was willing to find the depths of the rabbit hole in order to be with her. She was disgusted he couldn’t tell the difference between lemonade and limeade. She learned that water bottles are no longer just to hold liquid, but they''re also status symbols. Clyde blue enemies flash dots wocka maze monsters ghosts red chaser. I hear that Nancy is very pretty. I think I will buy the red car, or I will lease the blue one.', 'assets/images/news/new_8.jpg');

INSERT INTO news (inst_id, date, title, description, image_url) VALUES (5, 'Mon Nov 29 05:26:13 BRT 2021', 'I hear that Nancy is very pretty.', 'Ambusher maze wocka wocka fruit Pac-Man Fever arcade Galaxian Boss power up intermission. Pac-Man Namco Toru Iwatani Pac-Man Fever maze dots. High score Feigned Ignorance maze lives video game Apple slow guy chaser pizza missing slice dots blue. She was disgusted he couldn’t tell the difference between lemonade and limeade. Pac-Man bell ghosts Pokey strawberry flash blue enemies Namco Japan chaser dots dots Pakkuman. Poison ivy grew through the fence they said was impenetrable. Patricia loves the sound of nails strongly pressed against the chalkboard. The beauty of the sunset was obscured by the industrial cranes. Key Crybaby slow guy maze dots Power Pellets flash Midway chaser Pinky cherry Puck Man ghosts. Fluffy pink unicorns are a popular status symbol among macho men.', 'assets/images/news/new_9.jpg');

INSERT INTO news (inst_id, date, title, description, image_url) VALUES (5, 'Mon Nov 29 14:54:55 BRT 2021', 'The old apple revels in its authority.', 'Patricia loves the sound of nails strongly pressed against the chalkboard. She had the gift of being able to paint songs. Pac-Man Inky bashfull orange dots blue enemies ghosts Toru Iwatani Puck Man power up. Clyde blue enemies flash dots wocka maze monsters ghosts red chaser. High score Feigned Ignorance maze lives video game Apple slow guy chaser pizza missing slice dots blue. Fluffy pink unicorns are a popular status symbol among macho men. She was disgusted he couldn’t tell the difference between lemonade and limeade. He hated that he loved what she hated about hate. I hear that Nancy is very pretty. He was willing to find the depths of the rabbit hole in order to be with her.', 'assets/images/news/new_10.jpg');

INSERT INTO news (inst_id, date, title, description, image_url) VALUES (6, 'Mon Nov 29 23:26:15 BRT 2021', 'I hear that Nancy is very pretty.', 'She was disgusted he couldn’t tell the difference between lemonade and limeade. Pac-Man bell ghosts Pokey strawberry flash blue enemies Namco Japan chaser dots dots Pakkuman. Patricia loves the sound of nails strongly pressed against the chalkboard. Orange fickle blue guy maze chase. She had the gift of being able to paint songs. Apple Speedy maze wocka wocka flash chase Pakkuman paku-paku dots pizza missing slice. Flying fish few by the space station. Don''t put peanut butter on the dog''s nose. Ghosts dots cherry Blinky Pac-Man Power Pellets fruit. Ambusher maze wocka wocka fruit Pac-Man Fever arcade Galaxian Boss power up intermission.', 'assets/images/news/new_11.jpg');

INSERT INTO news (inst_id, date, title, description, image_url) VALUES (6, 'Mon Nov 29 23:54:13 BRT 2021', 'The old apple revels in its authority.', 'Shadow pink ghosts kill screen yellow disk video game maze console power up dots Midway. Pac-Man bell ghosts Pokey strawberry flash blue enemies Namco Japan chaser dots dots Pakkuman. As she walked along the street and looked in the gutter, she realized facemasks had become the new cigarette butts. Clyde blue enemies flash dots wocka maze monsters ghosts red chaser. He found his art never progressed when he literally used his sweat and tears. The beauty of the sunset was obscured by the industrial cranes. Pac-Man Inky bashfull orange dots blue enemies ghosts Toru Iwatani Puck Man power up. Poison ivy grew through the fence they said was impenetrable. She was disgusted he couldn’t tell the difference between lemonade and limeade. The external scars tell only part of the story.', 'assets/images/news/new_12.jpg');

INSERT INTO news (inst_id, date, title, description, image_url) VALUES (7, 'Mon Nov 29 16:05:34 BRT 2021', 'I hear that Nancy is very pretty.', 'High score Feigned Ignorance maze lives video game Apple slow guy chaser pizza missing slice dots blue. Pac-Man Inky bashfull orange dots blue enemies ghosts Toru Iwatani Puck Man power up. Don''t put peanut butter on the dog''s nose. Clyde blue enemies flash dots wocka maze monsters ghosts red chaser. Ambusher maze wocka wocka fruit Pac-Man Fever arcade Galaxian Boss power up intermission. Ghosts dots cherry Blinky Pac-Man Power Pellets fruit. Arcade cabinets retro Melon dots maza Pac-Man chase red Namco fruit wocka paku-paku 1980. I hear that Nancy is very pretty. He hated that he loved what she hated about hate. Apple Speedy maze wocka wocka flash chase Pakkuman paku-paku dots pizza missing slice.', 'assets/images/news/new_13.jpg');

INSERT INTO news (inst_id, date, title, description, image_url) VALUES (7, 'Mon Nov 29 17:26:31 BRT 2021', 'The old apple revels in its authority.', 'Shadow dots strawberry Pac-Man Midway chaser Pinky kill screen. High score Feigned Ignorance maze lives video game Apple slow guy chaser pizza missing slice dots blue. The old apple revels in its authority. He hated that he loved what she hated about hate. I think I will buy the red car, or I will lease the blue one. Apple Speedy maze wocka wocka flash chase Pakkuman paku-paku dots pizza missing slice. The beauty of the sunset was obscured by the industrial cranes. He had a hidden stash underneath the floorboards in the back room of the house. Pac-Man Inky bashfull orange dots blue enemies ghosts Toru Iwatani Puck Man power up. The external scars tell only part of the story.', 'assets/images/news/new_14.jpg');

INSERT INTO news (inst_id, date, title, description, image_url) VALUES (8, 'Mon Nov 29 07:20:05 BRT 2021', 'I hear that Nancy is very pretty.', 'Pac-Man Namco Toru Iwatani Pac-Man Fever maze dots. He had a hidden stash underneath the floorboards in the back room of the house. She learned that water bottles are no longer just to hold liquid, but they''re also status symbols. Patricia loves the sound of nails strongly pressed against the chalkboard. Shadow dots strawberry Pac-Man Midway chaser Pinky kill screen. Pac-Man bell ghosts Pokey strawberry flash blue enemies Namco Japan chaser dots dots Pakkuman. Fluffy pink unicorns are a popular status symbol among macho men. I hear that Nancy is very pretty. Pac-Man Inky bashfull orange dots blue enemies ghosts Toru Iwatani Puck Man power up. Poison ivy grew through the fence they said was impenetrable.', 'assets/images/news/new_15.jpg');

INSERT INTO news (inst_id, date, title, description, image_url) VALUES (8, 'Mon Nov 29 08:34:00 BRT 2021', 'The old apple revels in its authority.', 'Shadow dots strawberry Pac-Man Midway chaser Pinky kill screen. The external scars tell only part of the story. He was willing to find the depths of the rabbit hole in order to be with her. He found his art never progressed when he literally used his sweat and tears. Ghosts dots cherry Blinky Pac-Man Power Pellets fruit. Arcade cabinets retro Melon dots maza Pac-Man chase red Namco fruit wocka paku-paku 1980. She learned that water bottles are no longer just to hold liquid, but they''re also status symbols. Fluffy pink unicorns are a popular status symbol among macho men. She was disgusted he couldn’t tell the difference between lemonade and limeade. Clyde blue enemies flash dots wocka maze monsters ghosts red chaser.', 'assets/images/news/new_16.jpg');

INSERT INTO news (inst_id, date, title, description, image_url) VALUES (9, 'Mon Nov 29 10:35:13 BRT 2021', 'I hear that Nancy is very pretty.', 'He was willing to find the depths of the rabbit hole in order to be with her. High score Feigned Ignorance maze lives video game Apple slow guy chaser pizza missing slice dots blue. I think I will buy the red car, or I will lease the blue one. Orange fickle blue guy maze chase. The external scars tell only part of the story. I hear that Nancy is very pretty. Don''t put peanut butter on the dog''s nose. As she walked along the street and looked in the gutter, she realized facemasks had become the new cigarette butts. He hated that he loved what she hated about hate. She was disgusted he couldn’t tell the difference between lemonade and limeade.', 'assets/images/news/new_17.jpg');

INSERT INTO news (inst_id, date, title, description, image_url) VALUES (9, 'Mon Nov 29 21:26:43 BRT 2021', 'The old apple revels in its authority.', 'Pac-Man Inky bashfull orange dots blue enemies ghosts Toru Iwatani Puck Man power up. As she walked along the street and looked in the gutter, she realized facemasks had become the new cigarette butts. He was willing to find the depths of the rabbit hole in order to be with her. High score Feigned Ignorance maze lives video game Apple slow guy chaser pizza missing slice dots blue. Poison ivy grew through the fence they said was impenetrable. Don''t put peanut butter on the dog''s nose. Pac-Man Namco Toru Iwatani Pac-Man Fever maze dots. Pac-Man bell ghosts Pokey strawberry flash blue enemies Namco Japan chaser dots dots Pakkuman. She had the gift of being able to paint songs. I hear that Nancy is very pretty.', 'assets/images/news/new_18.jpg');
