INSERT INTO institutions (username, name, password, image_url, category, address, phone, description) VALUES ('casacaminho', 'Instituto Casa do Caminho', '1234567', 'assets/images/inst-profile/inst_9.png', 6, 'R. Padre Rolim, 222 - Santa Efigênia, Belo Horizonte - MG, 30130-090', '(31) 3586-3856', 'Instituição de apoio às pessoas com Câncer. Vivem de doações, inclusive o salário dos funcionários são providos por doações. Promovem bazares para angariar fundos e sempre precisam de ajuda.');
INSERT INTO institutions (username, name, password, image_url, category, address, phone, description) VALUES ('familiasCarentes', 'Associação Das Famílias Carentes De Belo Horizonte', '12345678', 'assets/images/inst-profile/inst_3.png', 0, 'R. Islândia, 196 - Sala 6 - Europa, Belo Horizonte - MG, 31620-430', '(31) 3458-9070', 'A Associação das Famílias Carentes de Belo Horizonte é uma entidade de direito privado, sem fins lucrativos, de caráter assistencial e filantrópico, que tem como principal finalidade amparar as famílias carentes, por meio do desenvolvimento e execução de programas sociais.');
INSERT INTO institutions (username, name, password, image_url, category, address, phone, description) VALUES ('fundacao_sara', 'Fundação Sara', '12345678', 'assets/images/inst-profile/inst_2.png', 1, 'R. André Luís, 415 - Canelas II, Montes Claros - MG, 39402-384', '(38) 3214-5500', 'Prestar assistência social às crianças e adolescentes com câncer e ser agente de promoção de conhecimentos e de melhorias do tratamento oncológico.');
INSERT INTO institutions (username, name, password, image_url, category, address, phone, description) VALUES ('salvação_army', 'Exército de Salvação', '12345678', 'assets/images/inst-profile/inst_2.png', 0, 'R. Maravilhas, 25 - Providência, Belo Horizonte - MG, 31814-040', '(31) 3433-3563', 'O Exército de Salvação existe para salvar almas, edificar os santos e servir a humanidade sofredora, motivado pelo amor a Deus, em nome de Jesus, sem discriminação.');
INSERT INTO institutions (username, name, password, image_url, category, address, phone, description) VALUES ('SantaBernadete', 'Casa Santa Bernadete', '123456778', 'assets/images/inst-profile/inst_6.png', 3, 'R. Gentil Gonzaga, 181 - Canelas, Montes Claros - MG, 39402-661', '(38) 3222-6055', ' A instituição acolhe jovens e adultos em situação de vulnerabilidade social com diagnóstico de câncer e em tratamento ambulatorial de radioterapia e/ou quimioterapia.');
INSERT INTO institutions (username, name, password, image_url, category, address, phone, description) VALUES ('salvação_army', 'Exército de Salvação', '12345678', 'assets/images/inst-profile/inst_5.png', 4, 'R. Maravilhas, 25 - Providência, Belo Horizonte - MG, 31814-040', '(31) 3433-3563', '');
INSERT INTO institutions (username, name, password, image_url, category, address, phone, description) VALUES ('doce_lar', 'Fundação da Terceira Idade Doce Lar', '1234562278', 'assets/images/inst-profile/inst_6.png', 5, 'Rua do Campo s/n - Agrovila, Porto Seguro - BA, 45810-000', '(73) 99819-0151', 'Casa de acolhimento da terceira idade, que vive de doações e sempre realiza campanhas para o recebimento de doações e divulgação do projeto');
INSERT INTO institutions (username, name, password, image_url, category, address, phone, description) VALUES ('apae_bahia', 'APAE PORTO SEGURO - BAHIA', '1234567', 'assets/images/inst-profile/inst_9.png', 6, 'Av. do Trab., 53 - Campinho, Porto Seguro - BA, 45810-000', '(73) 98109-2161', 'Somos uma rede sem fins lucrativos que, há mais de 60 anos, se dedica na defesa dos direitos e na prestação de serviços à pessoa com deficiência no Brasil. A APAE é responsável pela inclusão social em diversos níveis de milhares de pessoas ao longo de sua história. ');
INSERT INTO institutions (username, name, password, image_url, category, address, phone, description) VALUES ('velha_lar', 'Lar das velhinhas', '12345678', 'assets/images/inst-profile/inst_5.png', 5, 'R. Dom João Pimenta, 65 - Centro, Montes Claros - MG, 39400-003', '(38) 3221-1299', 'O Centro Feminino de Longa Permanecia “Lar das Velhinhas” é uma entidade civil, filantrópica, sem fins lucrativos, de cunho social, que presta Serviço de Acolhimento Institucional para pessoas idosas gênero feminino dando-lhes assistência alimentar, fornecendo-lhes atividades recreativas, abrigo e proteção.');
