-- MySQL Script generated by MySQL Workbench
-- qui 07 abr 2022 15:13:24
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `Carousel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Carousel` ;

CREATE TABLE IF NOT EXISTS `Carousel` (
  `ID` INT NOT NULL,
  `ImageURL` VARCHAR(100) NULL,
  `Descripition` VARCHAR(100) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `ID_UNIQUE` ON `Carousel` (`ID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Institutions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Institutions` ;

CREATE TABLE IF NOT EXISTS `Institutions` (
  `ID` INT NOT NULL,
  `User` VARCHAR(45) NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `ImageURL` VARCHAR(100) NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Category` VARCHAR(45) NOT NULL,
  `Address` VARCHAR(100) NOT NULL,
  `Phone` VARCHAR(45) NOT NULL,
  `Descripition` VARCHAR(100) NULL,
  PRIMARY KEY (`ID`, `User`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `ID_UNIQUE` ON `Institutions` (`ID` ASC) VISIBLE;

CREATE UNIQUE INDEX `User_UNIQUE` ON `Institutions` (`User` ASC) VISIBLE;

CREATE UNIQUE INDEX `Name_UNIQUE` ON `Institutions` (`Name` ASC) VISIBLE;

CREATE UNIQUE INDEX `Address_UNIQUE` ON `Institutions` (`Address` ASC) VISIBLE;

CREATE UNIQUE INDEX `Phone_UNIQUE` ON `Institutions` (`Phone` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `News`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `News` ;

CREATE TABLE IF NOT EXISTS `News` (
  `ID` INT NOT NULL,
  `Title` VARCHAR(45) NOT NULL,
  `ImageURL` VARCHAR(100) NULL,
  `Day` INT(2) NOT NULL,
  `Month` INT(2) NOT NULL,
  `Year` INT(4) NOT NULL,
  `Descripition` VARCHAR(100) NULL,
  `Institutions_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `Institutions_ID`),
  CONSTRAINT `fk_News_Institutions`
    FOREIGN KEY (`Institutions_ID`)
    REFERENCES `Institutions` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `ID_UNIQUE` ON `News` (`ID` ASC) VISIBLE;

CREATE INDEX `fk_News_Institutions_idx` ON `News` (`Institutions_ID` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
